---
functional:
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
---
non-functional:
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть доступен на различных устройствах
- Сайт должен иметь мобильную версию
- Сайт должен быть способен обрабатывать большое количество трафика
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
---
implicit:
- Необходимо выполнять требования закона о персональных данных и политике конфиденциальности
- Сайт должен предоставлять информацию пользователю о наличии тех или иных товаров
- Итоговое оформление заказа происходит, после указания контактных данных покупателя 
